[tool.ruff]
# Maximum line length
line-length = 88

# Target Python version
target-version = "py310"

# Enable all rules by default
select = ["E", "F", "W", "C", "B", "RUF"]

# Ignore specific rules if needed
ignore = ["E501"]  # example: ignore line-length warnings

# Optional: show verbose output
# verbose = true
