[tool.ruff]

# Maximum line length
line-length = 120

# File type to exclude from linting
exclude = [".ipynb", ".docx"]

# Target Python version
target-version = "py313"

# Select all linting rules
[tool.ruff.lint]
select = ["E", "F", "W", "C", "B", "RUF", "I", "SIM"]

# Optional: show verbose output
# verbose = true
