# Generated by Django 5.2.6 on 2025-09-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("required_skills", models.CharField(max_length=255)),
                ("job_description_summary", models.CharField(max_length=500)),
                ("salary", models.IntegerField()),
                ("contact_information", models.CharField(max_length=255)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
