name: Jobsika CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Create a virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Activate a virtual environment
      run: |
        source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run lint (ruff)
      run: |
        pip install ruff
        ruff check .

    - name: Run tests
      run: |
        python manage.py test
